"""
Write Runbook node — persists a successful recovery plan.

When an LLM-generated plan successfully fixes an issue, we save it
as a runbook so the next time this failure signature is seen, we can
skip the LLM and execute it deterministically.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime

from homeostat.state import AgentState, IncidentOutcome

logger = logging.getLogger(__name__)


def write_runbook(state: AgentState) -> AgentState:
    """
    Save the successful plan to DynamoDB.

    Input state keys:  failure_signature, plan, current_alert, diagnosis
    Output state keys: outcome, incident_log
    """
    from homeostat.memory.client import RunbookClient

    log = list(state.get("incident_log", []))
    plan = state.get("plan")
    signature = state.get("failure_signature")

    # If this was Tier-0, we don't write a new runbook
    if state.get("is_tier0"):
        log.append(f"[{_now()}] WRITE_RUNBOOK: Tier-0 handled this natively, skipping write")
        return {"outcome": IncidentOutcome.RESOLVED, "incident_log": log}

    # If we executed an existing runbook, we just update its stats (not fully implemented here yet)
    # But if it was generated by the LLM, we save it as a new runbook.
    if plan and plan.generated_by == "llm" and signature:
        try:
            client = RunbookClient()
            # Convert ActionPlan to dict format for storage
            steps = [
                {
                    "tool": s.tool,
                    "command": s.command,
                    "description": s.description
                }
                for s in plan.steps
            ]
            client.save_runbook(
                failure_signature=signature,
                diagnosis=state.get("diagnosis", "Unknown diagnosis"),
                plan_steps=steps,
                rationale=plan.rationale,
            )
            log.append(f"[{_now()}] WRITE_RUNBOOK: ✓ Saved new runbook for {signature}")
            logger.info("Saved new runbook for signature: %s", signature)
        except Exception as exc:
            log.append(f"[{_now()}] WRITE_RUNBOOK: ✗ Failed to save runbook: {exc}")
            logger.error("Failed to save runbook: %s", exc)

    return {
        "outcome": IncidentOutcome.RESOLVED,
        "incident_log": log,
    }


def _now() -> str:
    return datetime.now(UTC).strftime("%H:%M:%S")
