---
# Kustomize base — all core manifests
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeostat

resources:
  - agent
  - event-watcher/deployment.yml
  - event-watcher/configmap.yml
  - prometheus/alert-rules.yml
