---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homeostat-agent
  namespace: homeostat
  labels:
    app.kubernetes.io/name: homeostat-agent
    app.kubernetes.io/part-of: homeostat
    app.kubernetes.io/managed-by: kustomize
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::975050226684:role/homeostat-agent
